version: '3'
services:
  api:
    build: /
    depends_on:
      - database
    volumes:
      - ./:/home/node/app
    ports:
      - 3001:3001

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1312
