version: '3'
services:
  api:
    build: ./
    depends_on:
      - database
    container_name: ExpressTS-API
    # Mesmo que `docker run -t (terminal)`
    tty: true
    # Mesmo que `docker run -i (interativo)`
    stdin_open: true
    ports:
      - 3001:3001
    volumes:
      - ./:/home/node/app

  database:
    image: mysql
    ports:
      - 3307:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
