version: '3'
services:
  api:
    build: ./
    volumes:
      - ./:/home/node/app
    ports:
      - 3001:3001
    depends_on:
      - database
  database:
    image: mysql
    ports:
      - 3307:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_DEVELOPMENT_PASSWORD}
